inizio lavoro su anguix_configurator

diff --git a/Anguix-files/usr/bin/nautilus-scripts-installer b/Anguix-files/usr/bin/nautilus-scripts-installer
--- a/Anguix-files/usr/bin/nautilus-scripts-installer
+++ b/Anguix-files/usr/bin/nautilus-scripts-installer
@@ -6,13 +6,24 @@ if [ $(whoami) != "root" ]; then
 echo 'devi avere i privilegi di root per eseguire questo script, usa "sudo nautilus-scripts-installer"'
 exit 0
 fi
-apt-get update &> /dev/null | echo "Aggiorno la lista dei pacchetti"
-apt-get -y install nautilus-actions |echo "Aggiorno o installo nautilus-actions"
-cp -rf /usr/share/nautilus-scripts-installer/nautilus-actions $HOME/.gconf/apps | echo "copio i files nella home" 
-chmod -R 777 $HOME/.gconf/apps/nautilus-actions |echo "cambio i permessi alla cartella"
-apt-get -y install mp3info mp3info-gtk |echo "Aggiorno o installo mp3info"
-if [ "$?" = "0" ];then
-echo "completato. Ora termina la sessione attuale per vedere i cambiamenti"
-else
-echo  "errore."
-fi
+case $1 in
+	install)
+		apt-get update &> /dev/null | echo "Aggiorno la lista dei pacchetti"
+		if [ -d $HOME/.gconf/apps/nautilus-actions ]; then
+		cp -rf $HOME/.gconf/apps/nautilus-actions $HOME/.gconf/apps/nautilus-actions.backup
+		fi
+		apt-get -y install nautilus-actions |echo "Aggiorno o installo nautilus-actions"
+		cp -rf /usr/share/nautilus-scripts-installer/nautilus-actions $HOME/.gconf/apps | echo "copio i files nella home" 
+		chmod -R 777 $HOME/.gconf/apps/nautilus-actions |echo "cambio i permessi alla cartella"
+		apt-get -y install mp3info mp3info-gtk &> /dev/null |echo "Aggiorno o installo mp3info"
+		if [ "$?" = "0" ];then
+		echo "completato. Ora termina la sessione attuale per vedere i cambiamenti"
+		else
+		echo  "errore."
+		fi
+	;;
+	remove)
+		mv $HOME/.gconf/apps/nautilus-actions.backup $HOME/.gconf/apps/nautilus-actions |echo "removing files"
+		echo "rimozione completata."
+	;;
+esac
